language: node_js

cache:
  directories:
  - node_modules

notifications:
  email: false

node_js:
  - 9

script:
  - yarn
  - yarn test:lint
  - yarn test:flow
  - yarn test:coverage
  - yarn build:prod
  - yarn build:storybook
