language: node_js

cache:
  directories:
  - node_modules

notifications:
  email: false

node_js:
  - 8
  - 9

script:
  - yarn
  - yarn lint
  - yarn test
  - yarn build:prod
  - yarn build:storybook
