// flow-typed signature: 0cd12755ecd5a7a93a409ffbd699067b
// flow-typed version: <<STUB>>/eslint-config-dom_v^1.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-dom/rules/react-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-dom/rules/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-dom/index' {
  declare module.exports: $Exports<'eslint-config-dom'>;
}
declare module 'eslint-config-dom/index.js' {
  declare module.exports: $Exports<'eslint-config-dom'>;
}
declare module 'eslint-config-dom/rules/react-a11y.js' {
  declare module.exports: $Exports<'eslint-config-dom/rules/react-a11y'>;
}
declare module 'eslint-config-dom/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-dom/rules/react'>;
}
