version: 2

jobs:
  # Build production
  build:
    docker:
      - image: circleci/node:9
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Branch }}-{{ .Revision }}
            - repo-cache-{{ .Branch }}-
            - repo-cache-
          name: Restore repo cache
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ .Revision }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}-
            - yarn-cache-
          name: Restore yarn cache
      - run:
          command: yarn build:prod
          name: Build production

  # Build storybook
  build-storybook:
    docker:
      - image: circleci/node:9
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Branch }}-{{ .Revision }}
            - repo-cache-{{ .Branch }}-
            - repo-cache-
          name: Restore repo cache
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ .Revision }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}-
            - yarn-cache-
          name: Restore yarn cache
      - run:
          command: yarn build:storybook
          name: Build storybook

  # Checkout repo
  checkout:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - save_cache:
          key: repo-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
          name: Saving repo cache

  # Install dependencies
  dependencies:
    docker:
      - image: circleci/node:9
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Branch }}-{{ .Revision }}
            - repo-cache-{{ .Branch }}-
            - repo-cache-
          name: Restore repo cache
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ .Revision }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}-
            - yarn-cache-
          name: Restore yarn cache
      - run:
          command: yarn install
          name: Install yarn dependencies
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ .Revision }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
          name: Saving yarn cache

  # Run tests
  test:
    docker:
      - image: circleci/node:9
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Branch }}-{{ .Revision }}
            - repo-cache-{{ .Branch }}-
            - repo-cache-
          name: Restore repo cache
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ .Revision }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}-
            - yarn-cache-
          name: Restore yarn cache
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          command: yarn test
          name: Jest tests

  # Flowtype
  test-flow:
    docker:
      - image: circleci/node:9
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Branch }}-{{ .Revision }}
            - repo-cache-{{ .Branch }}-
            - repo-cache-
          name: Restore repo cache
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ .Revision }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}-
            - yarn-cache-
          name: Restore yarn cache
      - run:
          command: yarn test:flow
          name: Lint

  # Lint
  test-lint:
    docker:
      - image: circleci/node:9
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Branch }}-{{ .Revision }}
            - repo-cache-{{ .Branch }}-
            - repo-cache-
          name: Restore repo cache
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ .Revision }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}-
            - yarn-cache-
          name: Restore yarn cache
      - run:
          command: yarn test:lint
          name: Lint


workflows:
  version: 2
  build-test:
    jobs:
      - checkout:
          filters:
            tags:
              ignore: /^v.*/
      - dependencies:
          filters:
            tags:
              ignore: /^v.*/
          requires:
            - checkout
      - test:
          filters:
            tags:
              ignore: /^v.*/
          requires:
            - checkout
            - dependencies
      - test-lint:
          filters:
            tags:
              ignore: /^v.*/
          requires:
            - checkout
            - dependencies
      - test-flow:
          filters:
            tags:
              ignore: /^v.*/
          requires:
            - checkout
            - dependencies
      - build:
          filters:
            tags:
              ignore: /^v.*/
          requires:
            - checkout
            - dependencies
            - test
            - test-lint
            - test-flow
      - build-storybook:
          filters:
            tags:
              ignore: /^v.*/
          requires:
            - checkout
            - dependencies
            - test
            - test-lint
            - test-flow
  build-test-deploy:
    jobs:
      - checkout:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - dependencies:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - checkout
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - checkout
            - dependencies
      - test-lint:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - checkout
            - dependencies
      - test-flow:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - checkout
            - dependencies
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - checkout
            - dependencies
            - test
            - test-lint
            - test-flow
      - build-storybook:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - checkout
            - dependencies
            - test
            - test-lint
            - test-flow
