version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: $CODECLIMATE_TOKEN

    docker:
      - image: circleci/node:9.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install yarn dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Lint
          command: yarn test:lint
      - run:
          name: Flow
          command: yarn test:flow
      - run:
          name: Test
          command: |
            ./cc-test-reporter before-build
            yarn test
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
      - run:
          name: Build App
          command: yarn build:prod
      - run:
          name: Build Storybook
          command: yarn build:storybook
